package org.myopenproject.pathfinding.test;

import org.myopenproject.pathfinding.*;

public class Test {
	private static final int MAX_A = 3;
	private static final int MAX_B = 4;
	
	public static void main(String[] args) {
		// Root node = (0, 0)
		Node root = new Node(new Bucket(MAX_A), new Bucket(MAX_B));
		// Target node = (2, 0)
		Node target = new Node(new Bucket(MAX_A, 2), new Bucket(MAX_B, 0));
		
		// Path generated by BFS algorithm
		Node pathBFS[] = new BreadthFirst().execute(root, target);
		// path generated by A* algorithm
		Node pathAStar[] = new AStar().execute(root, target);
		
		System.out.println("BFS:");
		AlgorithmUtil.printPath(pathBFS);
		
		System.out.println("A*:");
		AlgorithmUtil.printPath(pathAStar);
	}
}